### ISSUE TITLE
Customizing Scroll Behaviour

### ISSUE THREAD

**Issue by bennypowers** [valdrinkoshi/virtual-scroller#121]
I'd like to implement something like [scroll-snap](https://github.com/lucafalasco/scroll-snap) using `<virtual-scroller>`. To that end, it would be awesome if I could override the scrolling behaviour.

**Comment by domenic** [comment]
Hmm. My inclination is that this would be orthogonal to virtual-scroller, which just uses the browsers default scroll behavior. That is, if you want to customize scroll behavior, that's a more general ask, and virtual-scroller ideally shouldn't do anything special (just like iframes and `<div style="overflow: auto">` don't do anything special).

Is there a reason scroll-snap doesn't work with virtual-scroller? Alternately, do native CSS snap points work with virtual scroller?

**Comment by bennypowers** [comment]
When I tried using scroll snap, I had all sorts of weird behaviours - mostly elements jumping all over the screen. I had some success rolling my own with intersection observer and scrollIntoView

**Comment by domenic** [comment]
With the new approach outlined in the [explainer](https://github.com/valdrinkoshi/virtual-scroller/blob/master/README.md), this should work as I'd hoped above, with native platform features like scroll-snap "just working". Since this repository is now focused around a spec proposal (see https://github.com/valdrinkoshi/virtual-scroller/issues/158#issuecomment-480913127), I don't think there's much more to do here, so I'll close this.

But, to be clear, this will be an important thing for implementers of the proposal to get right, and we'll make sure to emphasize that in the spec and tests!
