### ISSUE TITLE
`will-change: transform` on the virtual-list children by default?

### ISSUE THREAD

**Issue by valdrinkoshi** [valdrinkoshi/virtual-scroller#38]
`<virtual-list>` positions its children with `position: absolute` and `transform: translate3d`.
Should it also style the children with `will-change: transform` by default?

There are some implications for animations, e.g. see section "Partial solution: set will-change: transform" here https://greensock.com/will-change
This might be mitigated by the fact that we need to position children with `position: absolute`, hence we're creating a stacking context for each.

**Comment by ojanvafai** [comment]
I think we should change it to do translate2d instead of translate3d. That part is uncontroversial, right?

Then there's the question of whether it' should do will-change by default or not and I think that's really a question of whether it makes sense to take on the overhead of every list item having it's own GPU layer vs. the cost of rerastering when scrolling the list.

**Comment by valdrinkoshi** [comment]
Here a jsbin to play with, it forces contaiment & animations 
code http://jsbin.com/caxosun/1/edit?html,output
demo http://output.jsbin.com/caxosun/1/quiet

**Comment by domenic** [comment]
How should we make a decision here, I wonder?

**Comment by rakina** [comment]
Closing this as this is related to the `virtual-scroller` prototype implementation and we intend to make this repository focus on the standards side of it.
