### ISSUE TITLE
scroll position is not kept on resize

### ISSUE THREAD

**Issue by valdrinkoshi** [valdrinkoshi/virtual-scroller#64]
To reproduce
- go to https://valdrinkoshi.github.io/virtual-list/demo/contacts/
- scroll down a couple items
- resize the window
- note that the scroll position gets offset by items changing their size

![bug-scroll-position](https://user-images.githubusercontent.com/6173664/39830388-26778f74-5376-11e8-8633-8b7d581893aa.gif)

**Comment by valdrinkoshi** [comment]
note to self: there's probably a bug on how we keep track of the first item offset - checkout https://developers.google.com/web/updates/2016/07/infinite-scroller#scroll_anchoring

**Comment by valdrinkoshi** [comment]
Layout already ensures that the scroll position is kept, and uses the first **rendered** item as an anchor. When _overhang > 0, items get positioned outside the viewport, so that they can be rendered before appearing into the screen when scrolling.

The example above shows a different requirement, where the user wants to use the first **visible** item as an anchor. This could be achieved by setting _overhang to 0, but the scrolling performance might suffer from it.

I can imagine other use cases where the user wants to use another item as an anchor, e.g. in a chat app, use the last item as the anchor when user scrolls to the bottom. Or in an horizontal carousel, use the center item as the anchor. In general, user requirement is that other items resize or window resize push the other items around the anchor item.

Would it make sense to rather expose a property for this? I think all we need is some sort of `anchorOffset: number`, which can be set as:
- `anchorOffset = overhang` => uses the first visible item as an anchor
- `anchorOffset = overhang + viewportSize / 2` => center item as an anchor
- `anchorOffset = overhang + viewportSize` => last item as an anchor

@domenic @graynorton wdyt?

**Comment by graynorton** [comment]
A couple of questions:

1) Do you envision this property as existing only on the layout, or would it be facaded up to `virtual-scroller` itself?

2) While the numeric value offers complete flexibility, it seems like it might be a bit fiddly and/or error-prone. In addition to numeric values, what if we were to accept a small number of string values for common cases like `start`, `middle` and `end`? If the user chose one of these, the implementation could do the math.

**Comment by domenic** [comment]
I tend to agree that a common-case enum of those three options would be best. I'm not sure the full flexibility of anchorOffset is needed.

@tabatkins do I recall there being some CSS proposal that controlled this type of thing? I.e. that allowed the scrollbar to "stick" to the bottom when resizing something like a chat window?

Also /cc @flackr for his thoughts.

**Comment by valdrinkoshi** [comment]
Yeah, I'd also vote for exposing a property that accepts only common-case options - we can still implement it internally with `anchorOffset`.
How should the items positioning work? imagine that on resize our anchor item changes it size (it becomes taller). For `start`, it makes sense to push down the items below the anchor, but that might not make sense for `middle` or `end`. Maybe push away items above and below for `middle`, and push items above for `end`? In other words, what anchor point within the anchor item should we use?

Another thing to consider is how all this relates to data changes, e.g. in the chat example, when user receives a new message while scrolled to the end of the list vs not. Should we suggest the `elem.scrollTop = elem.scrollHeight` trick for the "scrolled to the end of the list" case?

**Comment by flackr** [comment]
I'm not sure I understand how @tabatkins proposal works with inserted content if the inserted content pushes the ::after further than the proximity distance that we snap to. Does the fact that it was previously snapped mean that it must try to re-snap no matter how far it has moved?

I think that most use cases fall into one of the two you mentioned; however, the chat app scenario usually only snaps to end if you were snapped to the end before the change. Otherwise, I believe most chat apps (if they do anything at all) keep the top item snapped into place. For this purpose, I could imagine two parameters (whether we want to expose both right now or not), one for which part of the scroll viewport to anchor, and one for whether being scrolled to the end of the list snaps to an imaginary post-list item.

**Comment by tabatkins** [comment]
> Does the fact that it was previously snapped mean that it must try to re-snap no matter how far it has moved?

Yup! Note the last paragraph of [section 4.1.2](https://drafts.csswg.org/css-scroll-snap/#snap-strictness) - once you snap to the `::after` pseudoelement, you *stay* snapped to it, even if it gets shifted downwards by new content being inserted.

And it has the correct behavior for when you're *not* near the bottom - it just doesn't snap, so your scroll position just sits still regardless of what's going on around it.

**Comment by KevinDoughty** [comment]
Also, in a grid layout, the anchor item may at times move in the direction of the scroll axis. When scrolling vertically, if it is too close to the bottom or top, layout may not permit its position to stay fixed in the y-axis. For example if the viewport is narrow and only scrolled down one row, then resized much wider, the anchored item will not be able to remain where it is, it will move up to the top row. Likewise, if the viewport is narrow and scrolled down very nearly to the bottom, then resized wider, it will "bottom out" and be laid out onto or near the very last row, beyond which it cannot be scrolled, and so would appear to move down. In these cases I would expect the anchored item to be preserved and its location restored if the viewport is resized back to the original width.

**Comment by rakina** [comment]
Closing this as this is related to the `virtual-scroller` prototype implementation and we intend to make this repository focus on the standards side of it.
